# Generated by Django 4.1.5 on 2023-01-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('plan', models.ManyToManyField(related_name='pricing_feature', to='payments.paypalplan')),
            ],
        ),
        migrations.DeleteModel(
            name='features',
        ),
    ]
