# Generated by Django 4.1.5 on 2023-01-28 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_feature_delete_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalsubscription',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Client's Address"),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='country_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name="Client's Country"),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Client's Email"),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Expired'),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Expiry Date'),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='order_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Order key'),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='payment_completed',
            field=models.BooleanField(default=False, verbose_name='Payment Completed'),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='previous_pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_pricing', to='payments.paypalplan'),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Subscription Start Date'),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='total_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Amount Paid'),
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='upgrading_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrading_to', to='payments.paypalplan'),
        ),
    ]
