# Generated by Django 4.1.5 on 2023-01-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paypalsubscription_active_paypalsubscription_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalsubscription',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
