# Generated by Django 4.1.5 on 2023-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paypalsubscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalplan',
            name='has_trial',
            field=models.BooleanField(default=False, verbose_name='Has Trial Period'),
        ),
    ]
