version: '3'

services:
  server:
    build: .
    container_name: server
    mem_limit: 256m
    cpu_quota: 25000
    command: >
      sh -c "python ./code/manage.py makemigrations --noinput &&
             python ./code/manage.py migrate &&
             python ./code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./code/static:/static
    env_file:
      - ./code/.env
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    container_name: celery
    command: >
      sh -c "cd ./code && celery --app=core worker --loglevel=info"
    volumes:
      - .:/code
      - ./code/static:/static
    env_file:
      - ./code/.env
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - server
      - redis
      
  redis:
    image: "redis:alpine"
    container_name: redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/:/etc/nginx/conf.d/
      - ./code/static/:/app/static/
      - ./code/media/:/app/media/
    links:
      - server

  pgdb:
    image: postgres:15.1-alpine
    container_name: pgdb
    mem_limit: 128m
    cpu_quota: 12500
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db_data/:/var/lib/postgresql/data