# Generated by Django 4.1.5 on 2023-01-28 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(default=datetime.date.today, verbose_name='Created on')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AmazonCalc',
            fields=[
                ('calc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.calc')),
                ('desired_return_value', models.CharField(max_length=256, verbose_name='desired_return_value')),
                ('item_sold_price', models.CharField(max_length=256, verbose_name='item_sold_price')),
                ('shipping_weight', models.CharField(max_length=256, verbose_name='shipping_weight')),
                ('shipping_credit', models.CharField(max_length=256, verbose_name='shipping_credit')),
                ('item_cost', models.CharField(max_length=256, verbose_name='item_cost')),
                ('shipping_cost', models.CharField(max_length=256, verbose_name='shipping_cost')),
                ('miscellaneous_cost', models.CharField(max_length=256, verbose_name='miscellaneous_cost')),
                ('shipping_method', models.CharField(max_length=256, verbose_name='shipping_method')),
                ('computedCategoryFee', models.CharField(max_length=256, verbose_name='computedCategoryFee')),
                ('totalAmazonCost', models.CharField(max_length=256, verbose_name='totalAmazonCost')),
                ('total_cost', models.CharField(max_length=256, verbose_name='total_cost')),
                ('actual_profit', models.CharField(max_length=256, verbose_name='actual_profit')),
                ('computedProfitMargin', models.CharField(max_length=256, verbose_name='computedProfitMargin')),
                ('sellAtPrice', models.CharField(max_length=256, verbose_name='sellAtPrice')),
            ],
            bases=('manager.calc',),
        ),
        migrations.CreateModel(
            name='CustomCalc',
            fields=[
                ('calc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.calc')),
                ('Profit', models.CharField(max_length=256, verbose_name='Profit')),
                ('item_cost_price', models.CharField(max_length=256, verbose_name='item_cost_price')),
                ('shipping_charge', models.CharField(max_length=256, verbose_name='shipping_charge')),
                ('shipping_cost', models.CharField(max_length=256, verbose_name='shipping_cost')),
                ('sales_tax', models.CharField(max_length=256, verbose_name='sales_tax')),
                ('selling_cost_percent', models.CharField(max_length=256, verbose_name='selling_cost_percent')),
                ('fixed_platform_fee', models.CharField(max_length=256, verbose_name='fixed_platform_fee')),
                ('transaction_cost_percent', models.CharField(max_length=256, verbose_name='transaction_cost_percent')),
                ('fixed_transaction_cost', models.CharField(max_length=256, verbose_name='fixed_transaction_cost')),
                ('revenue', models.CharField(max_length=256, verbose_name='revenue')),
                ('Gross_Profit_Margin', models.CharField(max_length=256, verbose_name='Gross_Profit_Margin')),
                ('sellingPrice', models.CharField(max_length=256, verbose_name='sellingPrice')),
                ('Markup', models.CharField(max_length=256, verbose_name='Markup')),
                ('selling_cost', models.CharField(default='0', max_length=256, verbose_name='selling_cost')),
                ('total_cost', models.CharField(default='0', max_length=256, verbose_name='total_cost')),
                ('preset', models.BooleanField(default=False, verbose_name='preset')),
            ],
            bases=('manager.calc',),
        ),
        migrations.CreateModel(
            name='EbayCalc',
            fields=[
                ('calc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.calc')),
                ('item_sold_price', models.CharField(max_length=256, verbose_name='item_sold_price')),
                ('item_cost_price', models.CharField(max_length=256, verbose_name='item_cost_price')),
                ('ebay_fee', models.CharField(max_length=256, verbose_name='ebay_fee')),
                ('shipping_charge', models.CharField(max_length=256, verbose_name='shipping_charge')),
                ('shipping_cost', models.CharField(max_length=256, verbose_name='shipping_cost')),
                ('promotion', models.CharField(max_length=256, verbose_name='promotion')),
                ('other_fees', models.CharField(max_length=256, verbose_name='other_fees')),
                ('category', models.CharField(max_length=256, verbose_name='category')),
                ('ebay_store', models.CharField(max_length=256, verbose_name='ebay_store')),
                ('seller_status', models.CharField(max_length=256, verbose_name='seller_status')),
                ('computedTotalCost', models.CharField(max_length=256, verbose_name='computedTotalCost')),
                ('computedTotalProfit', models.CharField(max_length=256, verbose_name='computedTotalProfit')),
                ('computedTotalProfitPercent', models.CharField(max_length=256, verbose_name='computedTotalProfitPercent')),
            ],
            bases=('manager.calc',),
        ),
    ]
