# Generated by Django 4.1.5 on 2023-02-28 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_templates_remove_customcalc_calc_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('color', models.CharField(max_length=256, verbose_name='Color')),
                ('message', models.TextField(verbose_name='message')),
                ('sending_date', models.DateField(blank=True, null=True, verbose_name='sending_date')),
                ('sending_time', models.DateField(blank=True, null=True, verbose_name='sending_time')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('color', models.CharField(max_length=256, verbose_name='Color')),
                ('message', models.TextField(verbose_name='message')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
            ],
        ),
        migrations.DeleteModel(
            name='Templates',
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.template'),
        ),
    ]
