# Generated by Django 4.1.5 on 2023-02-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_memo_user_task_user_template_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='template_id'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='color',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='date_created',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sending_date',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='sending_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sending_time',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='sending_time'),
        ),
        migrations.AlterField(
            model_name='template',
            name='color',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='template',
            name='date_created',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
    ]
