# Generated by Django 4.1.5 on 2023-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_template_template_id_alter_memo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='template',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='template_id'),
        ),
    ]
