# Generated by Django 4.1.5 on 2023-03-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_task_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='contact'),
        ),
    ]
