# Generated by Django 4.1.5 on 2023-03-21 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0009_remove_task_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='url')),
                ('date_created', models.CharField(blank=True, max_length=256, null=True, verbose_name='date_created')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('color', models.CharField(blank=True, max_length=256, null=True, verbose_name='Color')),
                ('display_area', models.CharField(blank=True, max_length=256, null=True, verbose_name='Display Area')),
                ('template', models.CharField(blank=True, max_length=256, null=True, verbose_name='template_id')),
                ('alarm_date', models.CharField(blank=True, max_length=256, null=True, verbose_name='alarm_date')),
                ('alarm_time', models.CharField(blank=True, max_length=256, null=True, verbose_name='alarm_time')),
                ('date_created', models.CharField(blank=True, max_length=256, null=True, verbose_name='date_created')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
